### ISSUE TITLE
getTableRowsEx 会出现com.gxchain.client.exception.GXChainApiException

### ISSUE THREAD

**Issue by zhuxuyin** [gxchain/gxclient-java#1]
getTableRowsEx 会出现com.gxchain.client.exception.GXChainApiException: Bad Cast: Invalid cast from object_type to uint64 	at com.gxchain.client.rpc.impl.GXChainApiRestClientImpl.execute(GXChainApiRestClientImpl.java:48) 	at com.gxchain.client.rpc.impl.GXChainApiRestClientImpl.query(GXChainApiRestClientImpl.java:59) 	at com.gxchain.client.rpc.impl.GXChainApiRestClientImpl.getTableRowsEx(GXChainApiRestClientImpl.java:209) 	at com.gxchain.client.GXChainClient.getTableRowsEx(GXChainClient.java:663) 	at com.gxchain.client.GXChainClientTest.getTableRowsEx(GXChainClientTest.java:184) 	at

**Comment by liruobin402** [comment]
已修复
